import security.http
### Login
run #Login

### QUERY adminAppConfigurationMailSmtp

GRAPHQL http://localhost:8081/api/g

query AdminAppConfigurationMailSmtp {
    adminAppConfigurationMailSmtp {
        mail {smtp {
            from host port pollingIntervalSeconds
            requireTls secure username ssl {
                protocols checkserveridentity
            }
        }}
    }
}

### MUTATION adminAppConfigurationMailSmtp

GRAPHQL http://localhost:8081/api/g

mutation AdminAppConfigurationMailSmtpUpdate($mailSmtp: MailSmtpConfigurationForm) {
    adminAppConfigurationMailSmtpUpdate(mailSmtp: $mailSmtp) {
        mail {smtp {
            from host port pollingIntervalSeconds
            requireTls secure username ssl {
                protocols checkserveridentity
            }
        }}
    }
}

{
  "mailSmtp": {
    "from": "noreply@ght1pc9kc.fr",
    "host": "smtp.mailersend.net",
    "port": 587,
    "pollingIntervalSeconds": 60,
    "requireTls": true,
    "secure": true,
    "username": "MS_cqUkqT@test-q3enl6k25z842vwr.mlsender.net",
    "ssl": {
      "protocols": "TLSv1.3 TLSv1.2",
      "checkserveridentity": true
    }
  }
}

###