### Login
GRAPHQL http://localhost:8081/api/g

mutation Login($username: String!, $password: String!) {
    login(username: $username, password: $password) {
        _id _createdAt
        login name roles mail
    }
}

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### CurrentUser

GRAPHQL http://localhost:8081/api/g

query CurrentUser {
    currentUser {
        login name roles mail
    }
}

### Get User
GRAPHQL http://localhost:8081/api/g

query UserGet($id: ID) {
    userGet(id: $id) {
        _id _createdAt _createdBy _loginAt _loginIP login name mail roles
    }
}

{
  "id": "US01GS2KEG1VVTV78KBQFCX4VVJN"
}