-- refs #73
ALTER TABLE USERS
    ADD COLUMN USER_CREATED_AT DATETIME NOT NULL DEFAULT '2022-02-05 00:00:00';
ALTER TABLE USERS
    ADD COLUMN USER_LOGIN_AT DATETIME;
ALTER TABLE USERS
    ADD COLUMN USER_LOGIN_IP VARCHAR(45);
