INSERT INTO USERS (USER_ID, USER_LOGIN, USER_EMAIL, USER_NAME, USER_PASSWORD)
VALUES ('US01GYQD8QTMM2XPCT5CXKNSVGYZ', 'prometheus', 'actuator@prometheus.fr', 'Prometheus Collecteur',
        '$2a$10$LRmEbYZKfId7ywgwO6V98eFEUj0PAK3bqjRoh8Lgglinnxax.DFFK');

INSERT INTO USERS_ROLES (USRO_USER_ID, USRO_ROLE)
VALUES ('US01GYQD8QTMM2XPCT5CXKNSVGYZ', 'ACTUATOR');
