create table FEEDS_ERRORS
(
    FEER_FEED_ID     VARCHAR(64) not null primary key,
    FEER_SINCE       DATETIME,
    FEER_LAST_TIME   DATETIME,
    FEER_LAST_STATUS INTEGER(3),
    FEER_LAST_LABEL  TEXT
);
