---

receivers:
  filelog/containers:
    include: ["/var/lib/docker/containers/*/*.log"]
    exclude: ["/var/lib/docker/containers/f99b265fe440bbf8fb3f293adc49cf4739cfbd5766dc5b6714a21d3ec46c
6c5a/f99b265fe440bbf8fb3f293adc49cf4739cfbd5766dc5b6714a21d3ec46c6c5a-json.log"]
    start_at: end
    include_file_path: true
    include_file_name: false
    operators:
      - type: json_parser
        id: parser-docker
        output: extract_metadata_from_filepath
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      # Extract metadata from file path
      - type: regex_parser
        id: extract_metadata_from_filepath
        regex: '^.*containers/(?P<container_id>[^_]+)/.*log$'
        parse_from: attributes["log.file.path"]
        output: parse_body
      - type: move
        id: parse_body
        from: attributes.log
        to: body
        output: move_app
      - type: move
        id: move_app
        from: attributes["attrs"]["application"]
        to: resource.application
        output: add_source
      - type: add
        id: add_source
        field: resource["source"]
        value: "docker"
      - type: remove
        id: time
        field: attributes.time
      - type: remove
        id: remove_stream
        field: attributes.stream
      - type: remove
        id: remove_filepath
        field: attributes["log.file.path"]

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [filelog/containers]
      processors: []
      exporters: [logging]