### /auth/login
POST http://{{host}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username={{login}}&password={{password}}

### /auth/current
GET http://{{host}}/api/auth/current

### /news
GET http://{{host}}/api/news?_s=-publication&read=false&_pp=20&_p=1

### /api/stats
GET http://{{host}}/api/stats

### /news/:newsId/unmark/shared
PUT http://{{host}}/api/news/{{newId}}/unmark/shared

### /auth/logout
DELETE http://{{host}}/api/auth/logout
