---
version: "3.9"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  baywatch:
    image: 'marthym/baywatch:latest'
    labels:
      application: baywatch
    read_only: true
    environment:
      BAYWATCH_DNS_SERVERS: 9.9.9.9, 8.8.8.8, 2620:fe::fe
      BAYWATCH_HOME: /var/lib/baywatch
      BAYWATCH_IMGPROXY_ENABLE: 'false'
      BAYWATCH_LOG_LEVEL: DEBUG
    logging:
      options:
        labels: 'application'
    ports:
      - '8081:8081'
    volumes:
      - /home/marthym:/var/lib/baywatch
      - /tmp/baywatch:/tmp

  prometheus:
    image: prom/prometheus:v2.43.0
    network_mode: "host"
    volumes:
      - ./.compose/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:8.5.22
    network_mode: "host"
    user: "472"
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./.compose/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_SECURITY_ADMIN_USER: baywatch
      GF_SECURITY_ADMIN_PASSWORD: baywatch
      GF_USERS_ALLOW_SIGN_UP: false

  opentelemetry:
    image: otel/opentelemetry-collector-contrib:0.75.0
    network_mode: "host"
    user: '0:0'
    command: [--config=/etc/otel-collector-config.yaml]
    logging:
      driver: local
      options:
        max-size: 10m
    volumes:
      - './.compose/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro'
      - '/home/docker/containers:/var/lib/docker/containers:ro'