### QUERY List all raw feed
GRAPHQL {{racine}}/api/g

query AdminRawFeedFind($_p: Int, $_pp: Int, $_from: Int, $_to: Int, $_s: String
    $_id: [ID], $name: String, $url: String) {
    adminRawFeedFind(
        _p: $_p, _pp: $_pp, _from: $_from, _to: $_to, _s: $_s
        _id: $_id, name: $name, url: $url) {
        totalCount entities {
            _id name url icon description lastETag lastWatch error {
                level since message
            }
        }
    }
}

{
  "_p": 0,
  "_pp": 5,
  "_s": "+name"
}

### QUERY GET SMTP Server
GRAPHQL {{racine}}/api/g
Authorization: Bearer {{$auth.token("keycloak")}}

query AdministrationMobileAppGet($_id: ID) {
    administrationExternalServerGet(_id: $_id) {
        _id _createdAt _createdBy name weight type host port
        ... on ExternalMailFakerServer {
            configType
            cipher requireTls secure
            username password fakerAddress
        }
        ... on ExternalSftpServer {
            username privateKey passphrase rootDirectory
        }
    }
}

{
  "_id": "67c02a0d1f71d05390adf282",
  "id": "67c02a0d1f71d05390adf281"
}

### MUTATION CREATE SFTP server
GRAPHQL {{racine}}/api/g

mutation AdministrationExternalServerCreate($extServer:ExternalServerForm){
    administrationExternalServerCreate(extServer:$extServer){
        _id _createdAt _createdBy name type host port weight
        ...ExternalServerFragment
    }
}
fragment ExternalServerFragment on ExternalServer{
    ...on ExternalSftpServer{rootDirectory username passphrase privateKey}
    ...on ExternalMailFakerServer{secure requireTls cipher fakeAddress username password configType}
    ...on ExternalMailSmtpServer{secure requireTls cipher username password configType}
    ...on ExternalMailMssServer{secure requireTls cipher username password configType}
}

{
  "extServer": {
    "name": "sftp-test-server",
    "weight": 10,
    "type": "SIU_SSH_SFTP",
    "host": "sftp.botdesign.net",
    "port": 16340,
    "username": "okenobi",
    "passphrase": "mayTheForce",
    "rootDirectory": "/test",
    "privateKey": "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDTDCakG4\nfJ3RzLgAmnTMaIAAAAEAAAAAEAAABoAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlz\ndHAyNTYAAABBBCK5jLu4axH9C+GYxY5XPCtrPfE/rUd0ukxf3YOmlToLcGop1Q5z/85nsR\nS7zrG1T9ARYR2jIMfr661jAiP3AJQAAADAwRZZwtRlO7Md75rDlSSreQTtNoINNiF6nPwk\n7fiSWqU1G/glAMhHqm3mwh/gmMP8kzl+SxQVA8mxTPDf//Gbye69p8ley34wvQaeLnx7Ba\n4j/1wNRc+4FUxsqGqwcy6KQppQl9vmSY7q6voU3qQa8p0x+Ye15BPhsemsSZFaYiUL4Qk6\nivy2fNyWb5jVDpaMNicqKj1BnBa+DuLZQzCrhk3M3r/lThQ25Bpk3MrLCilcjwqAdJ7l1l\nRKG9EvyASp\n-----END OPENSSH PRIVATE KEY-----"
  }
}

