### GET request to example server
GRAPHQL {{racine}}/api/g

mutation Login($username: String!, $password: String!) {
    login(username: $username, password: $password) {
        _id
        _createdAt
        login
        name
        roles
        mail
    }
}

{
  "username": "{{login}}",
  "password": "{{password}}"
}
###