# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
#deleteDatasources:
#  - name: Prometheus
#    orgId: 1
#  - name: Loki
#    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:

  - name: Prometheus
    type: prometheus
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    # <string> json object of data that will be encrypted.
    version: 1
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    editable: false
