---

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          metrics_path: '/actuator/prometheus'
          basic_auth:
            username: "prometheus"
            password: "uzpUAANKgZXxbdk19AjfWmknKfGbP2wKzAAMCpHm"
          static_configs:
            - targets: [baywatch:8081]
