---

service:
  pipelines:
    logs:
      receivers: [filelog/containers]
      processors: [attributes, batch]
      exporters: [logging, loki]
    metrics:
      receivers: [prometheus]
#      processors: [batch]
      exporters: [prometheus]
