CREATE TABLE FEEDS
(
    FEED_ID         INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FEED_NAME       VARCHAR(60),
    FEED_URL        VARCHAR(500) NOT NULL,
    FEED_LAST_WATCH DATETIME
);

CREATE TABLE FOLDER
(
    FOLD_ID   INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FOLD_NAME VARCHAR(60)
);

CREATE TABLE FEEDS_FOLDER
(
    FEFO_FOLD_ID INTEGER NOT NULL,
    FEFO_FEED_ID INTEGER NOT NULL,

    PRIMARY KEY (FEFO_FOLD_ID, FEFO_FEED_ID),
    CONSTRAINT FK_FEFO_FEED FOREIGN KEY (FEFO_FEED_ID) REFERENCES FEEDS (FEED_ID),
    CONSTRAINT FK_FEFO_FOLD FOREIGN KEY (FEFO_FOLD_ID) REFERENCES FOLDER (FOLD_ID)
);

CREATE TABLE NEWS
(
    NEWS_FEED_ID     INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NEWS_TITLE       VARCHAR(250) NOT NULL,
    NEWS_DESCRIPTION TEXT,
    NEWS_PUBLICATION DATETIME     NOT NULL,
    NEWS_LINK        VARCHAR(500) NOT NULL UNIQUE,
    NEWS_STARED      BOOLEAN      NOT NULL DEFAULT FALSE
);

INSERT INTO FEEDS
VALUES (1, 'Test', 'https://www.clubic.com/feed/news.rss', null);