CREATE TABLE FEEDS
(
    FEED_ID         INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FEED_NAME       VARCHAR(60),
    FEED_URL        VARCHAR(500) NOT NULL,
    FEED_LAST_WATCH DATETIME
);

CREATE TABLE NEWS
(
    NEWS_ID          VARCHAR(64)  NOT NULL PRIMARY KEY,
    NEWS_TITLE       VARCHAR(250) NOT NULL,
    NEWS_DESCRIPTION TEXT,
    NEWS_PUBLICATION DATETIME     NOT NULL,
    NEWS_LINK        VARCHAR(500) NOT NULL,
    NEWS_STARED      BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE NEWS_FEEDS
(
    NEFE_NEWS_ID VARCHAR(64) NOT NULL,
    NEFE_FEED_ID INTEGER     NOT NULL,

    CONSTRAINT PK_NEWS_FEEDS PRIMARY KEY (NEFE_NEWS_ID, NEFE_FEED_ID),
    CONSTRAINT FK_NEFE_NEWS_ID FOREIGN KEY (NEFE_NEWS_ID) REFERENCES NEWS (NEWS_ID),
    CONSTRAINT FK_NEFE_FEED_ID FOREIGN KEY (NEFE_FEED_ID) REFERENCES FEEDS (FEED_ID)
);

CREATE TABLE NEWS_USER_READ
(
    NEUR_NEWS_ID UUID NOT NULL,
    NEUR_USER_ID INTEGER,
    NEUR_IS_READ BOOLEAN,

    CONSTRAINT PK_NEWS_USER_READ PRIMARY KEY (NEUR_NEWS_ID, NEUR_USER_ID),
    CONSTRAINT PK_NEWS_USER_READ PRIMARY KEY (NEUR_NEWS_ID, NEUR_USER_ID),
    CONSTRAINT FK_NEUR_NEWS_ID FOREIGN KEY (NEUR_NEWS_ID) REFERENCES NEWS (NEWS_ID)
);

INSERT INTO FEEDS
VALUES (1, 'Test', 'https://www.clubic.com/feed/news.rss', null),
       (2, 'Reddit', 'https://www.reddit.com/r/programming/top/.rss', null);
