{
 "title": "Baywatch",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": "label_values(application)" },
   { "name": "level", "label": "level", "query": "label_values(level)" }
  ]
 },
 "panels": [
  {
   "title": "Baywatch Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{level=~\"${level}\", application=\"${application}\"}\n  | json \n  | line_format `{{ printf \"%-6.6s\" .level }} [{{ printf \"%20.20s\" .attributes_thread}}] : {{ .body}}`"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(bw_session_count_gauge{})" }
   ]
  },
  {
   "title": "Connexion Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(bw_login_seconds_count{reactor_status=\"completed\"}[$__rate_interval]))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Scraping Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "max(bw_scraping_seconds{})" }
   ]
  }
 ]
}