name: TruffleHog

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@041f07e9df901a1038a528e5525b0226d04dd5ea #v3.93.6
        with:
          extra_args: --results=verified,unknown
